from ._corp_assets_gateway import CorpAssetsGateway
from ._inventory_locations_gateway import InventoryLocationGateway
from eve.gateways._get_market_prices import GetMarketPricesGateway
from eve.gateways._get_type_info import GetTypeInfoGateway
from eve.gateways._get_markets_groups import GetMarketGroupsGateway
from eve.gateways._get_corp_assets_names import GetCorpAssetsNamesGateway
from ._foreign_structures_gateway import ForeignStructuresGateway
from eve.gateways._get_inventory_location_names import GetInventoryLocationNamesGateway
